name: Add to main project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add to main project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/adapt-security/projects/5
          github-token: ${{ secrets.PROJECTS_SECRET }}

  handle_precommit_pr:
    if: contains(github.event.pull_request.title, '[pre-commit.ci]')
    runs-on: ubuntu-latest
    
    steps:
      - name: Label pull request with "_bot"
        run: gh pr edit ${{ github.event.pull_request.number }} -R ${{ github.repository }} --add-label "_bot"
        env:
          GH_TOKEN: ${{ secrets.PROJECTS_SECRET }}
